"""enhance task workflow system

Revision ID: 68892a546aa1
Revises: ea7ea3f6f8fd
Create Date: 2026-07-01 14:58:13.174145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68892a546aa1'
down_revision: Union[str, Sequence[str], None] = 'ea7ea3f6f8fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('due_date', sa.String(length=50), nullable=True))
    op.add_column('tasks', sa.Column('created_at', sa.String(length=50), nullable=True))
    op.add_column('tasks', sa.Column('updated_at', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created_at')
    op.drop_column('tasks', 'due_date')
    # ### end Alembic commands ###
